version: '3.8'

services:
  frontend:
    image: kube-bench-ui-frontend:latest
    container_name: kube-bench-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      kube-bench-network:
        aliases:
          - frontend

  backend:
    image: kube-bench-ui-backend:latest
    container_name: kube-bench-backend
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=username
      - MYSQL_PASSWORD=your_password
      - MYSQL_DB=kube_bench
      - KUBE_BENCH_IMAGE=registry.cn-zhangjiakou.aliyuncs.com/cloudnativesec/kube-bench-zh:latest
    ports:
      - "5002:5002"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      kube-bench-network:
        aliases:
          - backend

  mysql:
    image: kube-bench-ui-db:latest
    container_name: kube-bench-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=kube_bench
      - MYSQL_USER=username
      - MYSQL_PASSWORD=your_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    entrypoint:
      - /bin/sh
      - -c
      - init.sh
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      kube-bench-network:
        aliases:
          - mysql

volumes:
  mysql_data: 

networks:
  kube-bench-network:
    external: true 